import { afterEach, describe, expect, it, TestRunner, vi } from "vitest";
import {
  createRecordStoryDecorator,
  getStorybookContext,
  installStoryRecorder,
  warnIfStoriesUndetected,
} from "./storybook";
import type * as testContext from "./test-context";
import { loadGetCurrentTest, type CurrentTask } from "./test-context";

vi.mock("./test-context", async (importOriginal) => {
  const original = await importOriginal<typeof testContext>();
  return {
    ...original,
    loadGetCurrentTest: vi.fn(original.loadGetCurrentTest),
  };
});

const target = globalThis as Record<PropertyKey, unknown>;

type Decorator = (storyFn: () => unknown, context: unknown) => unknown;

function createTask(overrides: Partial<CurrentTask> = {}): CurrentTask {
  return {
    id: "task-id",
    name: "test",
    fullName: "test",
    file: { name: "Button.test.tsx", filepath: "/src/Button.test.tsx" },
    meta: {},
    ...overrides,
  };
}

function getCurrentTask(): CurrentTask {
  return TestRunner.getCurrentTest() as unknown as CurrentTask;
}

/** Storybook's `setProjectAnnotations()` stores the composed annotations here. */
function setProjectAnnotations(annotations: { decorators: Decorator[] }) {
  target.globalProjectAnnotations = annotations;
}

function getProjectDecorators(): Decorator[] {
  return (target.globalProjectAnnotations as { decorators: Decorator[] })
    .decorators;
}

afterEach(() => {
  delete target.globalProjectAnnotations;
  delete target.__STORYBOOK_ADDONS_PREVIEW;
  delete target[Symbol.for("argos.storybook.recorderInstalled")];
  delete target[Symbol.for("argos.storybook.undetectedWarned")];
  vi.restoreAllMocks();
});

describe("getStorybookContext", () => {
  it("returns null for a test that renders no story", () => {
    expect(getStorybookContext(createTask())).toBeNull();
  });

  it("reads the story of a test generated by @storybook/addon-vitest", () => {
    // The composed story is a function carrying the story's fields.
    const story = Object.assign(() => null, {
      id: "components-button--primary",
      tags: ["dev", "button"],
      parameters: { tags: ["legacy"] },
      play: async () => {},
    });
    const task = createTask({
      meta: { storyId: "components-button--primary" },
      context: { story },
    });
    expect(getStorybookContext(task)).toEqual({
      source: "addon-vitest",
      story: {
        id: "components-button--primary",
        tags: ["dev", "button", "legacy"],
        play: true,
      },
    });
  });

  it("does not take a story id on the task meta alone for the addon", () => {
    // Anyone can set `task.meta`: without the addon's composed story on the
    // context, it is not a story test.
    const task = createTask({
      meta: { storyId: "components-button--primary" },
    });
    expect(getStorybookContext(task)).toBeNull();
  });

  it("reads the story recorded for a portable story", () => {
    const task = createTask({
      meta: {
        argosStory: {
          id: "components-button--primary",
          tags: ["dev"],
          play: false,
        },
      },
    });
    expect(getStorybookContext(task)).toEqual({
      source: "portable-stories",
      story: { id: "components-button--primary", tags: ["dev"], play: false },
    });
  });

  it.each([
    // A meta with neither `title` nor `id`.
    "composedstory--default",
    // A CSF Factories story composed outside the indexer, so without a name.
    "factories-chip--unnamed-story",
  ])("leaves out the placeholder id %s", (id) => {
    const task = createTask({
      meta: { argosStory: { id, tags: [], play: false } },
    });
    expect(getStorybookContext(task)).toEqual({
      source: "portable-stories",
      story: null,
    });
  });

  it("keeps the id of a meta with an `id` but no `title`", () => {
    const task = createTask({
      meta: {
        argosStory: {
          id: "design-system-button--primary",
          tags: [],
          play: false,
        },
      },
    });
    expect(getStorybookContext(task)?.story?.id).toBe(
      "design-system-button--primary",
    );
  });
});

describe("createRecordStoryDecorator", () => {
  it("records a story on the test that rendered it, not on later ones", () => {
    const testA = createTask({ id: "a", meta: {} });
    const testB = createTask({ id: "b", meta: {} });
    let current: CurrentTask | undefined = testA;
    const decorator = createRecordStoryDecorator(() => current);
    const context = { id: "components-button--primary", tags: [] };

    decorator(() => "story", context);
    expect(testA.meta?.argosStory).toMatchObject({
      id: "components-button--primary",
    });

    // The story mounted by test A renders again while test B runs.
    current = testB;
    decorator(() => "story", context);
    expect(testB.meta?.argosStory).toBeUndefined();

    // Test B rendering a story of its own still records it.
    decorator(() => "story", { id: "components-button--secondary", tags: [] });
    expect(testB.meta?.argosStory).toMatchObject({
      id: "components-button--secondary",
    });
  });

  it("does not attribute a story rendered outside any test", () => {
    const test = createTask({ meta: {} });
    let current: CurrentTask | undefined = undefined;
    const decorator = createRecordStoryDecorator(() => current);
    const context = { id: "components-button--primary", tags: [] };

    // Rendered in a `beforeAll` hook, then again during the test.
    decorator(() => "story", context);
    current = test;
    decorator(() => "story", context);
    expect(test.meta?.argosStory).toBeUndefined();
  });
});

describe("installStoryRecorder", () => {
  it("records on the current test the story a decorator renders", async () => {
    await installStoryRecorder();
    const userDecorator: Decorator = (storyFn) => storyFn();
    setProjectAnnotations({ decorators: [userDecorator] });

    const decorators = getProjectDecorators();
    expect(decorators).toHaveLength(2);
    expect(decorators[0]).toBe(userDecorator);

    const rendered = decorators[1]!(() => "story", {
      id: "components-button--primary",
      title: "Components/Button",
      tags: ["dev", "button"],
      parameters: { tags: ["legacy"] },
      playFunction: async () => {},
    });
    expect(rendered).toBe("story");

    expect(getStorybookContext(getCurrentTask())).toEqual({
      source: "portable-stories",
      story: {
        id: "components-button--primary",
        tags: ["dev", "button", "legacy"],
        play: true,
      },
    });
  });

  it("covers annotations set before it is installed", async () => {
    setProjectAnnotations({ decorators: [] });
    await installStoryRecorder();
    expect(getProjectDecorators()).toHaveLength(1);
  });

  it("leaves Storybook alone when the current test is out of reach", async () => {
    vi.mocked(loadGetCurrentTest).mockRejectedValueOnce(
      new Error("Vitest not reachable"),
    );
    await expect(installStoryRecorder()).resolves.toBeUndefined();
    setProjectAnnotations({ decorators: [] });
    expect(getProjectDecorators()).toHaveLength(0);
  });

  it("leaves frozen annotations alone", async () => {
    await installStoryRecorder();
    expect(() =>
      setProjectAnnotations(Object.freeze({ decorators: [] })),
    ).not.toThrow();
    expect(getProjectDecorators()).toHaveLength(0);
  });

  it("does not fail when the annotations global cannot be redefined", async () => {
    vi.spyOn(Object, "defineProperty").mockImplementationOnce(() => {
      throw new TypeError("Cannot redefine property: globalProjectAnnotations");
    });
    await expect(installStoryRecorder()).resolves.toBeUndefined();
  });

  it("adds its decorator only once", async () => {
    await installStoryRecorder();
    setProjectAnnotations({ decorators: [] });
    // Installed again, e.g. by the setup file of another test file.
    await installStoryRecorder();
    // And the same annotations set again.
    const annotations = target.globalProjectAnnotations;
    target.globalProjectAnnotations = annotations;
    expect(getProjectDecorators()).toHaveLength(1);
  });
});

describe("@argos-ci/vitest/storybook", () => {
  it("exports annotations recording the story each test renders", async () => {
    const { decorators } = await import("./storybook-annotations");
    expect(decorators).toHaveLength(1);

    decorators[0]!(() => "story", {
      id: "components-button--primary",
      tags: [],
    });
    expect(getStorybookContext(getCurrentTask())?.story?.id).toBe(
      "components-button--primary",
    );
  });
});

describe("warnIfStoriesUndetected", () => {
  it("warns once when Storybook is loaded but no recorder is installed", () => {
    const warn = vi.spyOn(console, "warn").mockImplementation(() => {});
    target.__STORYBOOK_ADDONS_PREVIEW = {};

    warnIfStoriesUndetected();
    warnIfStoriesUndetected();

    expect(warn).toHaveBeenCalledTimes(1);
    expect(warn.mock.calls[0]![0]).toContain("setProjectAnnotations()");
  });

  it("does not warn once the recorder is installed", async () => {
    const warn = vi.spyOn(console, "warn").mockImplementation(() => {});
    target.__STORYBOOK_ADDONS_PREVIEW = {};
    await installStoryRecorder();
    setProjectAnnotations({ decorators: [] });

    warnIfStoriesUndetected();

    expect(warn).not.toHaveBeenCalled();
  });

  it("does not warn without Storybook", () => {
    const warn = vi.spyOn(console, "warn").mockImplementation(() => {});
    warnIfStoriesUndetected();
    expect(warn).not.toHaveBeenCalled();
  });
});
