import { afterEach, describe, expect, it, TestRunner, vi } from "vitest";
import { getStorybookContext, installStoryRecorder } from "./storybook";
import type * as testContext from "./test-context";
import { loadGetCurrentTest, type CurrentTask } from "./test-context";

vi.mock("./test-context", async (importOriginal) => {
  const original = await importOriginal<typeof testContext>();
  return {
    ...original,
    loadGetCurrentTest: vi.fn(original.loadGetCurrentTest),
  };
});

const target = globalThis as Record<string, unknown>;

type Decorator = (storyFn: () => unknown, context: unknown) => unknown;

function createTask(overrides: Partial<CurrentTask> = {}): CurrentTask {
  return {
    id: "task-id",
    name: "test",
    fullName: "test",
    file: { name: "Button.test.tsx", filepath: "/src/Button.test.tsx" },
    meta: {},
    ...overrides,
  };
}

/** Storybook's `setProjectAnnotations()` stores the composed annotations here. */
function setProjectAnnotations(annotations: { decorators: Decorator[] }) {
  target.globalProjectAnnotations = annotations;
}

function getProjectDecorators(): Decorator[] {
  return (target.globalProjectAnnotations as { decorators: Decorator[] })
    .decorators;
}

describe("getStorybookContext", () => {
  it("returns null for a test that renders no story", () => {
    expect(getStorybookContext(createTask())).toBeNull();
  });

  it("reads the story of a test generated by @storybook/addon-vitest", () => {
    // The composed story is a function carrying the story's fields.
    const story = Object.assign(() => null, {
      tags: ["dev", "button"],
      play: async () => {},
    });
    const task = createTask({
      meta: { storyId: "components-button--primary" },
      context: { story },
    });
    expect(getStorybookContext(task)).toEqual({
      source: "addon-vitest",
      story: {
        id: "components-button--primary",
        tags: ["dev", "button"],
        play: true,
      },
    });
  });

  it("reads the story recorded for a portable story", () => {
    const task = createTask({
      meta: {
        argosStory: {
          id: "components-button--primary",
          tags: ["dev"],
          play: false,
          placeholderId: false,
        },
      },
    });
    expect(getStorybookContext(task)).toEqual({
      source: "portable-stories",
      story: { id: "components-button--primary", tags: ["dev"], play: false },
    });
  });

  it("leaves out the placeholder id of a portable story", () => {
    const task = createTask({
      meta: {
        argosStory: {
          id: "composedstory--default",
          tags: [],
          play: false,
          placeholderId: true,
        },
      },
    });
    expect(getStorybookContext(task)).toEqual({
      source: "portable-stories",
      story: null,
    });
  });
});

describe("installStoryRecorder", () => {
  afterEach(() => {
    delete target.globalProjectAnnotations;
  });

  it("records on the current test the story a decorator renders", async () => {
    await installStoryRecorder();
    const userDecorator: Decorator = (storyFn) => storyFn();
    setProjectAnnotations({ decorators: [userDecorator] });

    const decorators = getProjectDecorators();
    expect(decorators).toHaveLength(2);
    expect(decorators[0]).toBe(userDecorator);

    const rendered = decorators[1]!(() => "story", {
      id: "components-button--primary",
      title: "Components/Button",
      tags: ["dev", "button"],
      playFunction: async () => {},
    });
    expect(rendered).toBe("story");

    const task = TestRunner.getCurrentTest() as unknown as CurrentTask;
    expect(getStorybookContext(task)).toEqual({
      source: "portable-stories",
      story: {
        id: "components-button--primary",
        tags: ["dev", "button"],
        play: true,
      },
    });
  });

  it("flags a story id built from a Storybook placeholder", async () => {
    await installStoryRecorder();
    setProjectAnnotations({ decorators: [] });

    // A CSF Factories story composed outside the indexer has no export name.
    getProjectDecorators()[0]!(() => "story", {
      id: "factories-chip--unnamed-story",
      title: "Factories/Chip",
      name: "Unnamed Story",
      tags: [],
    });

    const task = TestRunner.getCurrentTest() as unknown as CurrentTask;
    expect(getStorybookContext(task)).toEqual({
      source: "portable-stories",
      story: null,
    });
  });

  it("covers annotations set before it is installed", async () => {
    setProjectAnnotations({ decorators: [] });
    await installStoryRecorder();
    expect(getProjectDecorators()).toHaveLength(1);
  });

  it("leaves Storybook alone when the current test is out of reach", async () => {
    // Vitest 4.0 in browser mode cannot load `vitest/suite`.
    vi.mocked(loadGetCurrentTest).mockRejectedValueOnce(
      new TypeError("Failed to resolve module specifier 'vitest/suite'"),
    );
    await expect(installStoryRecorder()).resolves.toBeUndefined();
    setProjectAnnotations({ decorators: [] });
    expect(getProjectDecorators()).toHaveLength(0);
  });

  it("adds its decorator only once", async () => {
    await installStoryRecorder();
    setProjectAnnotations({ decorators: [] });
    // Installed again, e.g. by the setup file of another test file.
    await installStoryRecorder();
    // And the same annotations set again.
    const annotations = target.globalProjectAnnotations;
    target.globalProjectAnnotations = annotations;
    expect(getProjectDecorators()).toHaveLength(1);
  });
});
