packages:
  - packages/*

catalog:
  '@types/node': ^20.19.40
  vitest: ^4.1.5

onlyBuiltDependencies:
  - '@swc/core'
  - chromedriver
  - cypress
  - edgedriver
  - esbuild
  - geckodriver
  - msw
  - nx
  - puppeteer
  - sharp
  - unrs-resolver

overrides:
  axios: ^1.16.0
  esbuild: ^0.25.10
  serialize-javascript: ^7.0.3
  undici: 8.1.0
  vite: ^7.3.2

