packages:
  - packages/*
onlyBuiltDependencies:
  - '@swc/core'
  - chromedriver
  - cypress
  - esbuild
  - msw
  - nx
  - puppeteer
  - sharp
ignoredBuiltDependencies:
  - edgedriver
  - geckodriver

catalog:
  vitest: ^3.2.4