packages:
  - packages/*
onlyBuiltDependencies:
  - '@swc/core'
  - chromedriver
  - cypress
  - esbuild
  - msw
  - nx
  - puppeteer
  - sharp
  - unrs-resolver
catalog:
  '@types/node': ^18.19.44
  vitest: ^3.2.4
