packages:
  - packages/*

catalog:
  '@types/node': ^20.19.30
  vitest: ^4.0.18

onlyBuiltDependencies:
  - '@swc/core'
  - chromedriver
  - cypress
  - edgedriver
  - esbuild
  - geckodriver
  - msw
  - nx
  - puppeteer
  - sharp
  - unrs-resolver

overrides:
  esbuild: ^0.25.10
