name: "Setup dependencies"
description: "Setup Node.js & install dependencies"
inputs:
  node-version:
    description: "Node.js version"
    required: false
    default: latest
runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v4
      name: Install pnpm

    - name: Install Node.js
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
      env:
        PUPPETEER_SKIP_DOWNLOAD: "true"
