/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/builds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createBuild"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deployments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createDeployment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deployments/{deploymentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDeployment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deployments/{deploymentId}/finalize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["finalizeDeployment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deployments/resolve/{domain}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["resolveDeploymentDomain"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/builds/finalize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["finalizeBuilds"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/cli/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange CLI authorization code for a token
         * @description Called by the CLI to exchange a PKCE authorization code for an API token.
         */
        post: operations["exchangeCliToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/github-actions/oidc/exchange": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange a GitHub Actions OIDC token for an Argos token
         * @description Called by GitHub Actions to exchange an OIDC token for a short-lived Argos project token.
         */
        post: operations["exchangeGitHubActionsOidcToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/github-actions/tokenless/exchange": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange a tokenless GitHub Actions token for an Argos token
         * @description Called by GitHub Actions to exchange a tokenless bearer token for a short-lived Argos project token. The provided commit and branch must match the GitHub workflow run.
         */
        post: operations["exchangeGitHubActionsTokenlessToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAuthProject"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/builds/{buildId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateBuild"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{owner}/{project}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getProject"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{owner}/{project}/builds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getProjectBuilds"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{owner}/{project}/builds/{buildNumber}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getBuild"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{owner}/{project}/builds/{buildNumber}/diffs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getBuildDiffs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{owner}/{project}/builds/{buildNumber}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a review on a specified build */
        post: operations["createReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description SHA1 hash */
        Sha1Hash: string;
        GitBranch: string;
        /** @description SHA256 hash */
        Sha256Hash: string;
        /**
         * @description A unique identifier for the build
         * @example 12345
         */
        BuildId: string;
        /** @description Screenshot input */
        ScreenshotInput: {
            key: string;
            name: string;
            baseName?: string | null;
            parentName?: string | null;
            metadata?: {
                /**
                 * @description Ignored. Can be set to get completions, validations and documentation in some editors.
                 * @example https://api.argos-ci.com/v2/screenshot-metadata.json
                 */
                $schema?: string;
                /** @description The URL of the page that was screenshotted */
                url?: string | null;
                /** @description An URL to an accessible preview of the screenshot */
                previewUrl?: string | null;
                viewport?: {
                    /** @description The width of the viewport */
                    width: number;
                    /** @description The height of the viewport */
                    height: number;
                } | null;
                /** @description The color scheme when the screenshot was taken */
                colorScheme?: ("light" | "dark") | null;
                /** @description The media type when the screenshot was taken */
                mediaType?: ("screen" | "print") | null;
                test?: {
                    /** @description The unique identifier of the test */
                    id?: string | null;
                    /** @description The title of the test */
                    title: string;
                    /** @description The path of titles leading to the test */
                    titlePath: string[];
                    /** @description The number of retries for the test */
                    retries?: number | null;
                    /** @description The current retry count */
                    retry?: number | null;
                    /** @description The repeat count for the test */
                    repeat?: number | null;
                    /** @description The location of the test in the source code */
                    location?: {
                        /** @description The located file */
                        file: string;
                        /** @description The line number in the file */
                        line: number;
                        /** @description The column number in the file */
                        column: number;
                    };
                    /** @description Annotations associated to the test */
                    annotations?: {
                        /** @description The type of annotation */
                        type: string;
                        /** @description The description of the annotation */
                        description?: string;
                        /** @description The location of the annotation in the source code */
                        location?: {
                            /** @description The located file */
                            file: string;
                            /** @description The line number in the file */
                            line: number;
                            /** @description The column number in the file */
                            column: number;
                        };
                    }[];
                    /** @description Tags associated to the test */
                    tags?: string[];
                } | null;
                browser?: {
                    /** @description The name of the browser */
                    name: string;
                    /** @description The version of the browser */
                    version: string;
                } | null;
                /** @description The automation library that generated the screenshot */
                automationLibrary: {
                    /** @description The name of the automation library */
                    name: string;
                    /** @description The version of the automation library */
                    version: string;
                };
                /** @description The Argos SDK that generated the screenshot */
                sdk: {
                    /** @description The name of the Argos SDK */
                    name: string;
                    /** @description The version of the Argos SDK */
                    version: string;
                };
                /** @description Storybook story metadata */
                story?: {
                    /** @description Unique ID of the story */
                    id: string;
                    /** @description Tags attached to the story */
                    tags?: string[];
                    /** @description Story mode */
                    mode?: string;
                    /** @description True if the story has a play function */
                    play?: boolean;
                } | null;
                /** @description Tags associated to the screenshot */
                tags?: string[];
            } | null;
            pwTraceKey?: string | null;
            threshold?: number | null;
            /** @default image/png */
            contentType: string;
        };
        /** @description Build metadata */
        BuildMetadata: {
            /** @description Test suite report */
            testReport?: {
                /**
                 * @description Status of the test suite
                 * @enum {string}
                 */
                status: "passed" | "failed" | "timedout" | "interrupted";
                stats?: {
                    /** @description Date when the test suite started */
                    startTime?: string;
                    /** @description Duration of the test suite in milliseconds */
                    duration?: number;
                };
            };
        };
        /**
         * @description The build number
         * @example 42
         */
        BuildNumber: string;
        /** @description Build */
        Build: {
            id: components["schemas"]["BuildId"];
            number: components["schemas"]["BuildNumberOutput"];
            /** @description The head reference of the build */
            head: components["schemas"]["BuildGitReference"];
            /** @description The base reference of the build */
            base: components["schemas"]["BuildGitReference"] | null;
            /** @description The status of the build */
            status: ("accepted" | "rejected") | ("no-changes" | "changes-detected") | ("expired" | "pending" | "progress" | "error" | "aborted");
            /** @description The conclusion of the build */
            conclusion: ("no-changes" | "changes-detected") | null;
            /** @description Stats of the diffs present in the build */
            stats: {
                /** @description Added snapshots */
                added: number;
                /** @description Removed snapshots */
                removed: number;
                /** @description Unchanged snapshots */
                unchanged: number;
                /** @description Changed snapshots */
                changed: number;
                /** @description Ignored snapshots */
                ignored: number;
                /** @description Failure screenshots */
                failure: number;
                /** @description Retry failure screenshots */
                retryFailure: number;
                /** @description Total number of snapshots */
                total: number;
            } | null;
            metadata: {
                /** @description Test suite report */
                testReport?: {
                    /**
                     * @description Status of the test suite
                     * @enum {string}
                     */
                    status: "passed" | "failed" | "timedout" | "interrupted";
                    stats?: {
                        /** @description Date when the test suite started */
                        startTime?: string;
                        /** @description Duration of the test suite in milliseconds */
                        duration?: number;
                    };
                };
            } | null;
            /**
             * Format: uri
             * @description The URL of the build
             */
            url: string;
            /** @description The notification payload for the build */
            notification: {
                description: string;
                context: string;
                github: {
                    /** @enum {string} */
                    state: "pending" | "success" | "error" | "failure";
                };
                gitlab: {
                    /** @enum {string} */
                    state: "pending" | "running" | "success" | "failed" | "canceled";
                };
            } | null;
        };
        /** @description Git reference */
        BuildGitReference: {
            /** @description The commit SHA */
            sha: components["schemas"]["Sha1Hash"];
            /** @description The branch name */
            branch: string;
        };
        /** @description Error response */
        Error: {
            error: string;
            details?: {
                message: string;
            }[];
        };
        /** @description Project */
        Project: {
            id: string;
            account: components["schemas"]["Account"];
            name: string;
            defaultBaseBranch: string;
            hasRemoteContentAccess: boolean;
        };
        /** @description Account */
        Account: {
            id: string;
            slug: string;
        };
        /** @description Page information */
        PageInfo: {
            /** @description Total number of items */
            total: number;
            /** @description Current page number */
            page: number;
            /** @description Number of items per page */
            perPage: number;
        };
        /** @description Snapshot diff */
        SnapshotDiff: {
            /** @description Unique identifier of the snapshot diff */
            id: string;
            /** @description Name of the snapshot diff */
            name: string;
            /**
             * @description Status of the snapshot diff
             * @enum {string}
             */
            status: "pending" | "removed" | "failure" | "added" | "changed" | "unchanged" | "retryFailure" | "ignored";
            /** @description Similarity score between snapshots */
            score: number | null;
            /** @description Grouping key for the snapshot diff */
            group: string | null;
            /** @description Parent name of the snapshot (usually the story id) */
            parentName: string | null;
            /** @description URL of the diff image */
            url: string | null;
            base: {
                /** @description Unique identifier of the snapshot */
                id: string;
                /** @description Name of the snapshot */
                name: string;
                metadata: {
                    /**
                     * @description Ignored. Can be set to get completions, validations and documentation in some editors.
                     * @example https://api.argos-ci.com/v2/screenshot-metadata.json
                     */
                    $schema?: string;
                    /** @description The URL of the page that was screenshotted */
                    url?: string | null;
                    /** @description An URL to an accessible preview of the screenshot */
                    previewUrl?: string | null;
                    viewport?: {
                        /** @description The width of the viewport */
                        width: number;
                        /** @description The height of the viewport */
                        height: number;
                    } | null;
                    /** @description The color scheme when the screenshot was taken */
                    colorScheme?: ("light" | "dark") | null;
                    /** @description The media type when the screenshot was taken */
                    mediaType?: ("screen" | "print") | null;
                    test?: {
                        /** @description The unique identifier of the test */
                        id?: string | null;
                        /** @description The title of the test */
                        title: string;
                        /** @description The path of titles leading to the test */
                        titlePath: string[];
                        /** @description The number of retries for the test */
                        retries?: number | null;
                        /** @description The current retry count */
                        retry?: number | null;
                        /** @description The repeat count for the test */
                        repeat?: number | null;
                        /** @description The location of the test in the source code */
                        location?: {
                            /** @description The located file */
                            file: string;
                            /** @description The line number in the file */
                            line: number;
                            /** @description The column number in the file */
                            column: number;
                        };
                        /** @description Annotations associated to the test */
                        annotations?: {
                            /** @description The type of annotation */
                            type: string;
                            /** @description The description of the annotation */
                            description?: string;
                            /** @description The location of the annotation in the source code */
                            location?: {
                                /** @description The located file */
                                file: string;
                                /** @description The line number in the file */
                                line: number;
                                /** @description The column number in the file */
                                column: number;
                            };
                        }[];
                        /** @description Tags associated to the test */
                        tags?: string[];
                    } | null;
                    browser?: {
                        /** @description The name of the browser */
                        name: string;
                        /** @description The version of the browser */
                        version: string;
                    } | null;
                    /** @description The automation library that generated the screenshot */
                    automationLibrary: {
                        /** @description The name of the automation library */
                        name: string;
                        /** @description The version of the automation library */
                        version: string;
                    };
                    /** @description The Argos SDK that generated the screenshot */
                    sdk: {
                        /** @description The name of the Argos SDK */
                        name: string;
                        /** @description The version of the Argos SDK */
                        version: string;
                    };
                    /** @description Storybook story metadata */
                    story?: {
                        /** @description Unique ID of the story */
                        id: string;
                        /** @description Tags attached to the story */
                        tags?: string[];
                        /** @description Story mode */
                        mode?: string;
                        /** @description True if the story has a play function */
                        play?: boolean;
                    } | null;
                    /** @description Tags associated to the screenshot */
                    tags?: string[];
                } | null;
                /** @description Width of the screenshot in pixels */
                width: number | null;
                /** @description Height of the screenshot in pixels */
                height: number | null;
                /**
                 * Format: uri
                 * @description Public URL of the snapshot
                 */
                url: string;
                /** @description Content type of the snapshot file */
                contentType: string;
            } | null;
            head: {
                /** @description Unique identifier of the snapshot */
                id: string;
                /** @description Name of the snapshot */
                name: string;
                metadata: {
                    /**
                     * @description Ignored. Can be set to get completions, validations and documentation in some editors.
                     * @example https://api.argos-ci.com/v2/screenshot-metadata.json
                     */
                    $schema?: string;
                    /** @description The URL of the page that was screenshotted */
                    url?: string | null;
                    /** @description An URL to an accessible preview of the screenshot */
                    previewUrl?: string | null;
                    viewport?: {
                        /** @description The width of the viewport */
                        width: number;
                        /** @description The height of the viewport */
                        height: number;
                    } | null;
                    /** @description The color scheme when the screenshot was taken */
                    colorScheme?: ("light" | "dark") | null;
                    /** @description The media type when the screenshot was taken */
                    mediaType?: ("screen" | "print") | null;
                    test?: {
                        /** @description The unique identifier of the test */
                        id?: string | null;
                        /** @description The title of the test */
                        title: string;
                        /** @description The path of titles leading to the test */
                        titlePath: string[];
                        /** @description The number of retries for the test */
                        retries?: number | null;
                        /** @description The current retry count */
                        retry?: number | null;
                        /** @description The repeat count for the test */
                        repeat?: number | null;
                        /** @description The location of the test in the source code */
                        location?: {
                            /** @description The located file */
                            file: string;
                            /** @description The line number in the file */
                            line: number;
                            /** @description The column number in the file */
                            column: number;
                        };
                        /** @description Annotations associated to the test */
                        annotations?: {
                            /** @description The type of annotation */
                            type: string;
                            /** @description The description of the annotation */
                            description?: string;
                            /** @description The location of the annotation in the source code */
                            location?: {
                                /** @description The located file */
                                file: string;
                                /** @description The line number in the file */
                                line: number;
                                /** @description The column number in the file */
                                column: number;
                            };
                        }[];
                        /** @description Tags associated to the test */
                        tags?: string[];
                    } | null;
                    browser?: {
                        /** @description The name of the browser */
                        name: string;
                        /** @description The version of the browser */
                        version: string;
                    } | null;
                    /** @description The automation library that generated the screenshot */
                    automationLibrary: {
                        /** @description The name of the automation library */
                        name: string;
                        /** @description The version of the automation library */
                        version: string;
                    };
                    /** @description The Argos SDK that generated the screenshot */
                    sdk: {
                        /** @description The name of the Argos SDK */
                        name: string;
                        /** @description The version of the Argos SDK */
                        version: string;
                    };
                    /** @description Storybook story metadata */
                    story?: {
                        /** @description Unique ID of the story */
                        id: string;
                        /** @description Tags attached to the story */
                        tags?: string[];
                        /** @description Story mode */
                        mode?: string;
                        /** @description True if the story has a play function */
                        play?: boolean;
                    } | null;
                    /** @description Tags associated to the screenshot */
                    tags?: string[];
                } | null;
                /** @description Width of the screenshot in pixels */
                width: number | null;
                /** @description Height of the screenshot in pixels */
                height: number | null;
                /**
                 * Format: uri
                 * @description Public URL of the snapshot
                 */
                url: string;
                /** @description Content type of the snapshot file */
                contentType: string;
            } | null;
        };
        /**
         * @description The build number
         * @example 42
         */
        BuildNumberOutput: unknown;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createBuild: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @description The commit the build is running on */
                    commit: components["schemas"]["Sha1Hash"];
                    /** @description The branch the build is running on */
                    branch: components["schemas"]["GitBranch"];
                    /** @description Keys of screenshot files */
                    screenshotKeys: components["schemas"]["Sha256Hash"][];
                    /** @description Keys of Playwright trace files */
                    pwTraceKeys?: components["schemas"]["Sha256Hash"][];
                    /** @description The name of the build (for multi-build setups) */
                    name?: string | null;
                    /** @description Whether to run the build in parallel */
                    parallel?: boolean | null;
                    /** @description A unique nonce for the parallel build */
                    parallelNonce?: string | null;
                    /** @description The pull request number */
                    prNumber?: number | null;
                    /** @description The head commit of the pull request */
                    prHeadCommit?: components["schemas"]["Sha1Hash"] | null;
                    /** @description The commit to use as a reference for the build */
                    referenceCommit?: components["schemas"]["Sha1Hash"] | null;
                    /** @description The branch to use as a reference for the build */
                    referenceBranch?: string | null;
                    /** @description The parent commits of the build */
                    parentCommits?: components["schemas"]["Sha1Hash"][] | null;
                    /** @description The mode in which the build is running */
                    mode?: ("ci" | "monitoring") | null;
                    /** @description The CI provider being used */
                    ciProvider?: string | null;
                    /** @description The version of the Argos SDK being used */
                    argosSdk?: string | null;
                    /** @description The ID of the current run */
                    runId?: string | null;
                    /** @description The attempt number of the current run */
                    runAttempt?: number | null;
                    /** @description Whether the build was skipped, not comparing anything and always succeeding */
                    skipped?: boolean | null;
                    /** @description Whether the build has been created in a merge queue */
                    mergeQueue?: boolean | null;
                    /** @description Pull request numbers aggregated by the merge queue build. Requires `mergeQueue` to be `true`. */
                    mergeQueuePrNumbers?: number[] | null;
                    /**
                     * @description Indicates whether this build contains only a subset of screenshots.
                     *     This is useful when a build is created from an incomplete test suite where some tests are skipped.
                     */
                    subset?: boolean | null;
                };
            };
        };
        responses: {
            /** @description Result of build creation */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        build: components["schemas"]["Build"];
                        screenshots: {
                            key: string;
                            /** Format: uri */
                            putUrl: string;
                        }[];
                        pwTraces: {
                            key: string;
                            /** Format: uri */
                            putUrl: string;
                        }[];
                    };
                };
            };
            /** @description Invalid parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createDeployment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @description The commit SHA */
                    commit: components["schemas"]["Sha1Hash"];
                    /** @description The branch name */
                    branch: components["schemas"]["GitBranch"];
                    /** @description The pull request number */
                    prNumber?: number | null;
                    /**
                     * @description The deployment environment. When omitted, it is inferred from `branch`: branches matching the configured production-branch glob are treated as `production`; all others default to `preview`.
                     * @enum {string}
                     */
                    environment?: "preview" | "production";
                    /** @description List of files to deploy */
                    files: {
                        path: string;
                        hash: components["schemas"]["Sha256Hash"];
                        size: number;
                        contentType: string;
                    }[];
                };
            };
        };
        responses: {
            /** @description Deployment created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        deploymentId: string;
                        uploadFiles: {
                            path: string;
                            hash: string;
                            /** Format: uri */
                            uploadUrl: string;
                        }[];
                    };
                };
            };
            /** @description Invalid parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getDeployment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The deployment ID */
                deploymentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deployment details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        /** @enum {string} */
                        status: "pending" | "ready" | "error";
                        /** @enum {string} */
                        environment: "preview" | "production";
                        branch: components["schemas"]["GitBranch"];
                        commitSha: components["schemas"]["Sha256Hash"];
                        /** Format: uri */
                        url: string;
                        createdAt: string;
                    };
                };
            };
            /** @description Invalid parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    finalizeDeployment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The deployment ID */
                deploymentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deployment finalized */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        /** @enum {string} */
                        status: "pending" | "ready" | "error";
                        /** @enum {string} */
                        environment: "preview" | "production";
                        branch: components["schemas"]["GitBranch"];
                        commitSha: components["schemas"]["Sha256Hash"];
                        /** Format: uri */
                        url: string;
                        createdAt: string;
                    };
                };
            };
            /** @description Invalid parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    resolveDeploymentDomain: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A deployment domain or URL */
                domain: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deployment domain resolved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        deploymentId: string;
                        projectId: string;
                        /** @enum {string} */
                        environment: "preview" | "production";
                        /** @enum {string} */
                        visibility: "private" | "public";
                    };
                };
            };
            /** @description Invalid parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    finalizeBuilds: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    parallelNonce: string;
                };
            };
        };
        responses: {
            /** @description Result of build finalization */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        builds: components["schemas"]["Build"][];
                    };
                };
            };
            /** @description Invalid parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    exchangeCliToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @description PKCE authorization code from the login flow */
                    code: string;
                    /** @description PKCE code verifier matching the code challenge */
                    code_verifier: string;
                };
            };
        };
        responses: {
            /** @description Token exchange successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Argos API token for CLI use */
                        token: string;
                    };
                };
            };
            /** @description Invalid parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    exchangeGitHubActionsOidcToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @description GitHub Actions OIDC token */
                    oidcToken: string;
                    /** @description GitHub repository in owner/name format */
                    repository?: string;
                    /** @description Expected commit SHA */
                    commit?: components["schemas"]["Sha1Hash"];
                    /** @description Expected branch name */
                    branch?: string;
                    /** @description Expected pull request number */
                    pullRequestNumber?: number;
                };
            };
        };
        responses: {
            /** @description Token exchange successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Short-lived Argos project token */
                        token: string;
                        /** @description Token expiration date as an ISO string */
                        expiresAt: string;
                    };
                };
            };
            /** @description Invalid parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    exchangeGitHubActionsTokenlessToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @description Argos tokenless GitHub Actions bearer token */
                    tokenlessToken: string;
                    /** @description Expected commit SHA */
                    commit: components["schemas"]["Sha1Hash"];
                    /** @description Expected branch name */
                    branch: string;
                };
            };
        };
        responses: {
            /** @description Token exchange successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Short-lived Argos project token */
                        token: string;
                        /** @description Token expiration date as an ISO string */
                        expiresAt: string;
                    };
                };
            };
            /** @description Invalid parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getAuthProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    updateBuild: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique identifier for the build */
                buildId: components["schemas"]["BuildId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    screenshots: components["schemas"]["ScreenshotInput"][];
                    parallel?: boolean | null;
                    parallelTotal?: number | null;
                    parallelIndex?: number | null;
                    metadata?: components["schemas"]["BuildMetadata"];
                };
            };
        };
        responses: {
            /** @description Result of build update */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        build: components["schemas"]["Build"];
                    };
                };
            };
            /** @description Invalid parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                owner: string;
                project: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getProjectBuilds: {
        parameters: {
            query?: {
                /** @description Number of items per page (max 100) */
                perPage?: string;
                /** @description Page number */
                page?: string;
                head?: string;
                headSha?: components["schemas"]["Sha1Hash"];
                /** @description Only return the latest builds created, unique by name and commit. */
                distinctName?: string;
            };
            header?: never;
            path: {
                owner: string;
                project: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of builds */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        pageInfo: components["schemas"]["PageInfo"];
                        results: components["schemas"]["Build"][];
                    };
                };
            };
            /** @description Invalid parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getBuild: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                owner: string;
                project: string;
                /** @description The build number */
                buildNumber: components["schemas"]["BuildNumber"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Build */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Build"];
                };
            };
            /** @description Invalid parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getBuildDiffs: {
        parameters: {
            query?: {
                /** @description Number of items per page (max 100) */
                perPage?: string;
                /** @description Page number */
                page?: string;
                /** @description Only return diffs that require review. Matches `changed`, `added`, and `removed`, except `removed` is excluded for subset builds. */
                needsReview?: string;
            };
            header?: never;
            path: {
                owner: string;
                project: string;
                /** @description The build number */
                buildNumber: components["schemas"]["BuildNumber"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of screenshot diffs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        pageInfo: components["schemas"]["PageInfo"];
                        results: components["schemas"]["SnapshotDiff"][];
                    };
                };
            };
            /** @description Invalid parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                owner: string;
                project: string;
                /** @description The build number */
                buildNumber: components["schemas"]["BuildNumber"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description Overall review conclusion for the build: "APPROVE" or "REQUEST_CHANGES"
                     * @enum {string}
                     */
                    conclusion: "APPROVE" | "REQUEST_CHANGES";
                    /**
                     * @description Optional per-snapshot review decisions. When omitted, only the build-level review is recorded.
                     * @default []
                     */
                    snapshots?: {
                        /** @description The ID of the snapshot to review */
                        id: string;
                        /**
                         * @description Review conclusion for this individual snapshot: "APPROVE" or "REQUEST_CHANGES"
                         * @enum {string}
                         */
                        conclusion: "APPROVE" | "REQUEST_CHANGES";
                    }[];
                };
            };
        };
        responses: {
            /** @description Review submitted successfully — returns the review */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        /** @enum {string} */
                        state: "approved" | "rejected";
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
