name: Trigger https://argos-ci.com/docs build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Call Vercel Build Hook
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_CA7x4b2WrAC80ELqOxJJYcvCX8kn/SpLzd2cg6b
